name: sistema_educativo
description: "Sistema educativo multiplataforma para colegios."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  url_launcher: 6.3.2
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  pdf: ^3.11.3
  excel: ^4.0.6
  printing: ^5.14.2
  open_filex: ^4.3.3
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  google_maps_flutter: 2.14.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  cloud_functions: ^6.0.0
  http: ^1.4.0
  flutter_typeahead: ^5.2.0
  collection: ^1.18.0
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  google_fonts: ^8.0.2

  # Firebase y servicios esenciales
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Manejo de estado y arquitectura
  provider: ^6.1.2

  # Navegacion declarativa
  go_router: ^12.1.3

  # Notificaciones
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.3.1

  # Íconos iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.jpeg
    - assets/logo_fondo.png
    - assets/pagina_inicio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"
                              
