name: sistema_educativo
description: "Sistema educativo multiplataforma para colegios."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  open_filex: ^4.3.3
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  cloud_functions: ^5.6.2
  http: ^1.4.0
  flutter_typeahead: ^5.2.0
  collection: ^1.18.0
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  flutter:
    sdk: flutter

  # Firebase y servicios esenciales
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # Manejo de estado y arquitectura
  provider: ^6.1.2

  # Notificaciones
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.3.1

  # Íconos iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"