// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'app_environment.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (AppEnvironment.isProduction) {
      if (kIsWeb) return productionWeb;
      if (defaultTargetPlatform == TargetPlatform.android)
        return productionAndroid;
      throw UnsupportedError(
        'Producción solo está configurada para web y Android.',
      );
    }
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjfpuzVCTvKEMdYGYjMa619SSJ1yL8Jho',
    appId: '1:732639994966:web:f71afd170b50235fe847f7',
    messagingSenderId: '732639994966',
    projectId: 'sistema-educativo-rl',
    authDomain: 'sistema-educativo-rl.firebaseapp.com',
    storageBucket: 'sistema-educativo-rl.firebasestorage.app',
    measurementId: 'G-JE21N6C0PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEpoXpp68zQHoSEvR00ToIggiiaHOLufI',
    appId: '1:732639994966:android:ad6ec170c7f782b8e847f7',
    messagingSenderId: '732639994966',
    projectId: 'sistema-educativo-rl',
    storageBucket: 'sistema-educativo-rl.firebasestorage.app',
  );

  static const productionWeb = FirebaseOptions(
    apiKey: 'AIzaSyBXPXXueD4pGhrM7TK9hLTuYQ2LLpsF-5Q',
    appId: '1:325430927285:web:4825f7f65a75fd6ee103fc',
    messagingSenderId: '325430927285',
    projectId: 'sistema-educativo-rl-prod',
    authDomain: 'sistema-educativo-rl-prod.firebaseapp.com',
    storageBucket: 'sistema-educativo-rl-prod.firebasestorage.app',
  );

  static const productionAndroid = FirebaseOptions(
    apiKey: 'AIzaSyBjvzhsUcfEXCZVW6pZxOCVdZsQJmU75rw',
    appId: '1:325430927285:android:2eecce415faf28dee103fc',
    messagingSenderId: '325430927285',
    projectId: 'sistema-educativo-rl-prod',
    storageBucket: 'sistema-educativo-rl-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHcaewhHeOi8QNpuFrZrUKu2sY3hF4Eo',
    appId: '1:732639994966:ios:cd30b8eca3c700efe847f7',
    messagingSenderId: '732639994966',
    projectId: 'sistema-educativo-rl',
    storageBucket: 'sistema-educativo-rl.firebasestorage.app',
    iosBundleId: 'com.example.sistemaEducativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHcaewhHeOi8QNpuFrZrUKu2sY3hF4Eo',
    appId: '1:732639994966:ios:cd30b8eca3c700efe847f7',
    messagingSenderId: '732639994966',
    projectId: 'sistema-educativo-rl',
    storageBucket: 'sistema-educativo-rl.firebasestorage.app',
    iosBundleId: 'com.example.sistemaEducativo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjfpuzVCTvKEMdYGYjMa619SSJ1yL8Jho',
    appId: '1:732639994966:web:84a76035429a7208e847f7',
    messagingSenderId: '732639994966',
    projectId: 'sistema-educativo-rl',
    authDomain: 'sistema-educativo-rl.firebaseapp.com',
    storageBucket: 'sistema-educativo-rl.firebasestorage.app',
    measurementId: 'G-T1SRXQPDS4',
  );
}
