import '../models/enrollment_field.dart';

const List<EnrollmentField> enrollmentFieldConfig = [
  EnrollmentField(
    name: 'anioInscripcion',
    label: 'Año lectivo',
    type: 'int',
    required: true,
    editableBy: ['admin'],
    defaultValue: 'currentYear',
  ),
  EnrollmentField(
    name: 'fechaInscripcion',
    label: 'Fecha de inscripción',
    type: 'datetime',
    required: true,
    editableBy: ['system'],
    defaultValue: 'now',
  ),
  EnrollmentField(
    name: 'nombresAlumno',
    label: 'Nombres del estudiante',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'apellidosAlumno',
    label: 'Apellidos del estudiante',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarNacimiento',
    label: 'Lugar de nacimiento',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'fechaNacimiento',
    label: 'Fecha de nacimiento',
    type: 'date',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'edad',
    label: 'Edad',
    type: 'int',
    required: false,
    editableBy: ['system'],
    formula: 'ageFromBirthDate',
  ),
  EnrollmentField(
    name: 'tipoSangre',
    label: 'Tipo de sangre',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'tiposSangre',
  ),
  EnrollmentField(
    name: 'rh',
    label: 'RH',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    options: ['+', '-'],
  ),
  EnrollmentField(
    name: 'tipoIdentidad',
    label: 'Tipo de documento',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'tiposDocumento',
  ),
  EnrollmentField(
    name: 'numeroIdentidad',
    label: 'Número de documento',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'direccionAlumno',
    label: 'Dirección de residencia',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'telefonoAlumno',
    label: 'Teléfono',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'epsEstudiante',
    label: 'EPS del estudiante',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'eps',
  ),
  EnrollmentField(
    name: 'nombrePadre',
    label: 'Nombre del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cedulaPadre',
    label: 'Cédula del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'emailPadre',
    label: 'Email del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularPadre',
    label: 'Celular del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarTrabajoPadre',
    label: 'Lugar donde labora el padre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'ocupacionPadre',
    label: 'Ocupación del padre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cargoPadre',
    label: 'Cargo del padre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'nombreMadre',
    label: 'Nombre de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cedulaMadre',
    label: 'Cédula de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'emailMadre',
    label: 'Email de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularMadre',
    label: 'Celular de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarTrabajoMadre',
    label: 'Lugar donde labora la madre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'ocupacionMadre',
    label: 'Ocupación de la madre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cargoMadre',
    label: 'Cargo de la madre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'tieneAcudienteDiferente',
    label: '¿El acudiente es diferente al padre o madre?',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'acudientePrincipal',
    label: '¿Quién es el acudiente principal?',
    type: 'enum',
    required: false,
    editableBy: ['padre'],
    options: ['padre', 'madre'],
  ),
  EnrollmentField(
    name: 'nombreAcudiente',
    label: 'Nombre del acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cedulaAcudiente',
    label: 'Cédula del acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'emailAcudiente',
    label: 'Email del acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularAcudiente',
    label: 'Celular del acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarTrabajoAcudiente',
    label: 'Lugar donde labora el acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'ocupacionAcudiente',
    label: 'Ocupación del acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cargoAcudiente',
    label: 'Cargo del acudiente',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'facturaElectronica',
    label: '¿A quién se le debe hacer la facturación electrónica?',
    type: 'enum',
    required: false,
    editableBy: ['padre'],
    options: ['padre', 'madre', 'acudiente', 'ninguno'],
  ),
  EnrollmentField(
    name: 'sedeAspirada',
    label: 'Sede',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'sedes',
  ),
  EnrollmentField(
    name: 'gradoAspirado',
    label: 'Grado',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'grados',
  ),
  EnrollmentField(
    name: 'nivelesCursadosInstitucion',
    label: 'Niveles o grados cursados en la institución',
    type: 'string',
    required: false,
    editableBy: ['admin', 'padre'],
  ),
  EnrollmentField(
    name: 'servicioLonchera',
    label: 'Lonchera',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'servicioAlmuerzo',
    label: 'Almuerzo',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'servicioTransporte',
    label: 'Transporte',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'servicioTransporteTipo',
    label: 'Tipo de transporte:',
    type: 'enum',
    required: false,
    editableBy: ['padre'],
    options: ['medio_tiempo', 'tiempo_completo'],
  ),
  EnrollmentField(
    name: 'observacionesPadres',
    label: 'Observaciones del estudiante',
    type: 'text',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'fueReferido',
    label: '¿Fue referido por algun padre o estudiante del colegio?',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'nombreReferido',
    label: 'Nombre del estudiante que lo refirió',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'nombrePadresReferentes',
    label: 'Nombre del padre que lo refirió',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'telefonoReferentes',
    label: 'Teléfono del padre que lo refirió',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularReferentes',
    label: 'Celular del padre que lo refirió',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
];
