import '../models/enrollment_section.dart';

/// Secciones declarativas del formulario de matrícula.
const List<EnrollmentSection> enrollmentSections = [
  EnrollmentSection(
    title: 'Datos del estudiante',
    fieldNames: [
      'anioInscripcion',
      'fechaInscripcion',
      'nombresAlumno',
      'apellidosAlumno',
      'lugarNacimiento',
      'fechaNacimiento',
      'edad',
      'tipoIdentidad',
      'numeroIdentidad',
      'tipoSangre',
      'rh',
      'direccionAlumno',
      'telefonoAlumno',
      'epsEstudiante',
      'groupId',
      'sedeAspirada',
    ],
  ),
  EnrollmentSection(
    title: 'Información del padre',
    fieldNames: [
      'nombrePadre',
      'cedulaPadre',
      'emailPadre',
      'celularPadre',
      'lugarTrabajoPadre',
      'ocupacionPadre',
      'cargoPadre',
    ],
  ),
  EnrollmentSection(
    title: 'Información de la madre',
    fieldNames: [
      'nombreMadre',
      'cedulaMadre',
      'emailMadre',
      'celularMadre',
      'lugarTrabajoMadre',
      'ocupacionMadre',
      'cargoMadre',
    ],
  ),
  EnrollmentSection(
    title: 'Información del acudiente',
    fieldNames: [
      'tieneAcudienteDiferente',
      'acudientePrincipal',
      'nombreAcudiente',
      'cedulaAcudiente',
      'emailAcudiente',
      'celularAcudiente',
      'lugarTrabajoAcudiente',
      'ocupacionAcudiente',
      'cargoAcudiente',
      'facturaElectronica',
    ],
  ),
  EnrollmentSection(
    title: 'Servicios y referencias',
    fieldNames: [
      'nivelesCursadosInstitucion',
      'servicioLonchera',
      'servicioAlmuerzo',
      'servicioTransporte',
      'servicioTransporteTipo',
      'fueReferido',
      'nombreReferido',
      'observacionesPadres',
      'nombrePadresReferentes',
      'telefonoReferentes',
      'celularReferentes',
    ],
  ),
];
