import '../models/enrollment_field.dart';

const List<EnrollmentField> enrollmentFieldConfig = [
  EnrollmentField(
    name: 'anioInscripcion',
    label: 'Año de inscripción',
    type: 'int',
    required: true,
    editableBy: ['admin'],
    defaultValue: 'currentYear',
  ),
  EnrollmentField(
    name: 'fechaInscripcion',
    label: 'Fecha de inscripción',
    type: 'datetime',
    required: true,
    editableBy: ['system'],
    defaultValue: 'now',
  ),
  EnrollmentField(
    name: 'nombresApellidosAlumno',
    label: 'Nombres y apellidos del estudiante',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarNacimiento',
    label: 'Lugar de nacimiento',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'fechaNacimiento',
    label: 'Fecha de nacimiento',
    type: 'date',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'edad',
    label: 'Edad',
    type: 'int',
    required: false,
    editableBy: ['system'],
    formula: 'ageFromBirthDate',
  ),
  EnrollmentField(
    name: 'tipoSangre',
    label: 'Tipo de sangre',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'tiposSangre',
  ),
  EnrollmentField(
    name: 'rh',
    label: 'RH',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    options: ['+', '-'],
  ),
  EnrollmentField(
    name: 'tipoIdentidad',
    label: 'Tipo de documento',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'tiposDocumento',
  ),
  EnrollmentField(
    name: 'numeroIdentidad',
    label: 'Número de documento',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'direccionAlumno',
    label: 'Dirección',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'telefonoAlumno',
    label: 'Teléfono',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'epsEstudiante',
    label: 'EPS del estudiante',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'eps',
  ),
  EnrollmentField(
    name: 'nombrePadre',
    label: 'Nombre del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cedulaPadre',
    label: 'Cédula del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'emailPadre',
    label: 'Email del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularPadre',
    label: 'Celular del padre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarTrabajoPadre',
    label: 'Lugar donde labora el padre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'ocupacionPadre',
    label: 'Ocupación del padre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cargoPadre',
    label: 'Cargo del padre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'nombreMadre',
    label: 'Nombre de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cedulaMadre',
    label: 'Cédula de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'emailMadre',
    label: 'Email de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularMadre',
    label: 'Celular de la madre',
    type: 'string',
    required: true,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'lugarTrabajoMadre',
    label: 'Lugar donde labora la madre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'ocupacionMadre',
    label: 'Ocupación de la madre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'cargoMadre',
    label: 'Cargo de la madre',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'sedeAspirada',
    label: 'Sede',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'sedes',
  ),
  EnrollmentField(
    name: 'gradoAspirado',
    label: 'Grado',
    type: 'enum',
    required: true,
    editableBy: ['padre'],
    optionsSource: 'grados',
  ),
  EnrollmentField(
    name: 'nivelesCursadosInstitucion',
    label: 'Niveles o grados cursados en la institución',
    type: 'string',
    required: false,
    editableBy: ['admin', 'padre'],
  ),
  EnrollmentField(
    name: 'servicioAlmuerzo',
    label: 'Almuerzo',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'servicioTransporte',
    label: 'Transporte',
    type: 'bool',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'observacionesPadres',
    label: 'Observaciones / recomendaciones de los padres',
    type: 'text',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'nombrePadresReferentes',
    label: 'Nombre de los padres (referentes)',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'telefonoReferentes',
    label: 'Teléfono de los padres (referentes)',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'celularReferentes',
    label: 'Celular de los padres (referentes)',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
  EnrollmentField(
    name: 'nombreReferido',
    label: 'Nombre del referido',
    type: 'string',
    required: false,
    editableBy: ['padre'],
  ),
];
